### ISSUE TITLE
Comparison to PHOENIX in the CaT region

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#139]
Hi,

I've synthesized a bunch of spectra in the 3000A to 10000A wavelength range using Korg on a logg/teff/feh/alpha grid that I can compare with PHOENIX. One of the features I observe is major difference around the CaT (in the wings particularly). 
![compar](https://user-images.githubusercontent.com/109513/201495261-cc78d275-779f-4bd7-8931-c3846f059ae1.png)
here's a T=4500K, logg=5, [Fe/H]=0 [a/Fe]=0 case
I understand that you are not responsible for PHOENIX, but I heard a view from an expert )) that we see here is more likely korg's deficiency rather than PHOENIX due to some kind of strong line treatment. Do you have any advice/opinion on that ?  Or maybe I'm not using the right options ? 
 
Thanks 

PS I just used the standard Korg synthesize call with MARCS models + all the lines from VALD + individual alpha element abundances specified according to [Fe/H], [a/Fe].

**Comment by ajwheeler** [comment]
> that we see here is more likely korg's deficiency rather than PHOENIX due to some kind of strong line treatment. Do you have any advice/opinion on that ?

My expectation is that this is correct, but I'm going to have to do some reading about PHOENIX's treatment of strong lines.  Thanks for bringing this to my attention.

**Comment by segasai** [comment]
The PHOENIX paper says this on strong lines (sec 2.2 https://www.aanda.org/articles/aa/full_html/2013/05/aa19058-12/aa19058-12.html )  "The next step was to activate a mode in PHOENIX that triggers the use of special line profiles, which we used for the Ca lines, for example. In this mode no convergence is checked, so we carried out five more iterations by default in order to stratify the atmosphere again properly. Finally, the high resolution spectrum was synthesised from this intermediate model."
Pointed by @alexji

**Comment by ajwheeler** [comment]
Thanks.  

I've been skimming the various PHOENIX papers, and I'm still unsure what they mean by "special" profiles.  Several papers mention that they use Doppler profiles for weak lines, and Voigt profiles for sufficiently strong lines, but it doesn't seem like that's what's being described here.

It's worth nothing (this is largely a note for my future self) that in section 2.3 of that paper, they say that they treat Ca II in NLTE.  That is likely to be more accurate than Korg, with the big caveat that NLTE calculations involve even more uncertain physical quantities than LTE ones, so systematics may be very important.  It's almost certainly not what's going on here, though, since NLTE will affect the line core much more strongly than the wings.

This may also come down to a difference between the MARCS and PHOENIX atmospheres, though the continua agree, so I don't think that's likely either.
![image](https://user-images.githubusercontent.com/711963/201994627-b8b7594d-2b6a-40d1-b951-b9ed42df4517.png)

**Comment by andycasey** [comment]
The description of how they treat strong lines is a little short. One other potential point of difference here is that I think the PHOENIX grid is entirely spherical geometry, and the MARCS models in this parameter range are all plane-parallel. But I doubt that would explain these differences.

**Comment by segasai** [comment]
I googled for 'special line profile' and could only find this reference https://iopscience.iop.org/article/10.3847/1538-3881/ab8d33 which also talks about special line profiles, but without going into details.
I'm going to ping @alexji again since he mentioned previously that he has seen aome strong line flag in MOOG. (i have no clue myself).

**Comment by andycasey** [comment]
The strong line flag in MOOG is used to tell MOOG that it should calculate opacities for a given line at all wavelengths. Otherwise MOOG calculates line contributions +/- some user-defined window in wavelength (usually ~2 Angstroms). Korg will calculate opacities until the line contribution relative to the continuum is small (as you saw with Balmer lines), which should work well for weak and strong lines. If it didn’t work well for CaT then we’d see the sharp cutoff in wavelength like you saw elsewhere. I think the “special line treatment” here (whatever it is) might be different. I’ll read the paper you linked.

**Comment by ajwheeler** [comment]
Agreed that spherical geometry is unlikely to be the culprit.  This paper lists H lines as the only ones with "special" profiles, but they be leaving something out.

**Comment by andycasey** [comment]
@segasai do you have the PHOENIX code, or just the pre-computed spectra using PHOENIX?

**Comment by segasai** [comment]
Here ftp://phoenix.astro.physik.uni-goettingen.de/AtmosFITS/ they have 64 layers and tau,temp,pgas,rho

**Comment by ajwheeler** [comment]
Andy tells me that these don't have electron partial pressures, which Korg relies on, so I can't compare Korg+PHOENIX atmosphere vs Korg+MARCS.  I'm hoping to remedy that soon, so we will be able to do the comparison eventually, just not yet.

**Comment by andycasey** [comment]
Out of interest, here is a comparison of the photospheric quantities. The models used were:

- Phoenix: `lte04500-5.00-0.0.PHOENIX-ACES-AGSS-COND-2011.ATMOS.fits`
- MARCS: `p4500_g+5.0_m0.0_t01_st_z+0.00_a+0.00_c+0.00_n+0.00_o+0.00_r+0.00_s+0.00.mod.gz`

So both have Teff = 4500, logg = 5.0, [M/H] = 0, [alpha/M] = 0, microturbulence = 1 km/s. By selecting PHOENIX models with [M/H] = 0 and [alpha/M] I could only find the "lte*" photospheres (no 'non-LTE' photospheres).

I assume \tau in PHOENIX files are Rosseland optical depths. Here's the comparison:

![phoenix](https://user-images.githubusercontent.com/504436/202039448-603d2141-86cf-4e8f-85e5-32bec9f46ba7.png)

The PHOENIX models go much shallower than the MARCS models, but the Ca II triplet lines form much deeper, so that's an unlikely explanation for the difference. 

The PHOENIX documentation page (https://phoenix.astro.physik.uni-goettingen.de/?page_id=108) says that they store electron partial pressure, but the FITS file I found on the FTP server definitely doesn't:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/504436/202040073-7cc2f7eb-8419-4329-928a-049c93a2e288.png">
 
(I think there's also a unit bug in the PHOENIX headers for stellar masses, because it implies the PHOENIX model I used is 600 M_\odot).

**Comment by alexji** [comment]
I think the easiest/best thing to do would be to contact one of the PHOENIX authors if they would be willing to send a few model atmospheres with the required quantities.

For the MOOG stuff: there was an ancient (no longer used) flag to do magic things with damping coefficients for specific strong lines. I suspect something similar happens in PHOENIX to better reproduce observed lines. As Adam said I think they use NLTE for some specific things too, but I think the damping treatment is more important here as it's a wing mismatch.

**Comment by segasai** [comment]
I gave a wrong link. this is the link to the v2.0 atmospheres
ftp://phoenix.astro.physik.uni-goettingen.de/v2.0/AtmosFITS/
 and these have the pe column

**Comment by andycasey** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/504436/202041550-00e34b72-2d8c-4842-9ffa-c5bfd9b7fbe5.png">

**Comment by andycasey** [comment]
With v2.0 atmosphere. Seems to be better agreement if \tau is at 5000 Angstroms. I'll try synthesize something now.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/504436/202042097-a993bfeb-9d96-4514-8aa0-8c5bc2b67f75.png">

**Comment by segasai** [comment]
I've just briefly looked at PHOENIX vs actual data.
I looked at stars from APOGEE with S5 1700D data.
This is a star with logg=4.566099, Teff=4992.816, M/H=-0.08617 according to APOGEE DR17.
and the 2DF data on that star was fitted by my PHOENIX interpolated models with teff=5250, logg=5, feh=-0.3
And here is the fit 
![s5star](https://user-images.githubusercontent.com/109513/202046445-81cd4ebb-723b-4c43-a851-d196901389dd.png)

Red is PHOENIX, black is data. The cores are not well fit, but wings look sensible, so I'd say that supports the view that PHOENIX is accurate here.

**Comment by andycasey** [comment]
Unfortunately we still need (physical) depth in these photosphere models in order to synthesise a spectrum with Korg. 

I'm also inclined to believe that PHOENIX is more accurate here, but we will need to understand why.

Out of interest, if you synthesize a Korg spectrum at the two possible sets of parameters (4993/4.57/-0.09 vs 5250/5.0/-0.3) and convolve them to match the data, how do those compare?

**Comment by segasai** [comment]
To answer the last question, I finally managed to substitute PHOENIX by Korg grid for my spectral fitter (rvspecfit), so I can now side to side compare interpolated Korg/PHOENIX. as well as refit say S5 data with Korg grid.
For the example star show above here're the plots for the two sets of parameters (4993/4.57/-0.09 vs 5250/5.0/-0.3)
The spectra are convolved to 1700D resolution. 
![image](https://user-images.githubusercontent.com/109513/202219467-528f8fe2-64e9-41f6-8da8-51ece7b8a4ac.png)

**Comment by segasai** [comment]
FWIW 

here's a side-by-side comparison of fits by interpolated PHOENIX vs vs interpolated Korg for the same star as shown above:
We can see the same CaT problems as discussed above. 
And also Alex pointed at the 8806 Mg line. 

![fig_phoe](https://user-images.githubusercontent.com/109513/202257183-e3a71369-cc0d-4d6f-9a56-c889445d98fa.png)
![fig_korg](https://user-images.githubusercontent.com/109513/202257186-dea26334-18d3-47b0-bdfe-80853ff9e9af.png)

**Comment by ajwheeler** [comment]
Korg doesn't need depth when doing calculations in plane-parallel, which a good approximation at logg=5.  I've synthesized spectra using the two atmospheres compared by Andy, and the difference looks very close to Sergey's original plot.
![image](https://user-images.githubusercontent.com/711963/202285405-8e4a7728-6826-4757-bc3c-ba844b96f536.png)

**Comment by alexji** [comment]
I took a quick look at the parser, it should be getting the VDW coefficient from the line list so not using the default Unsold approx.

Sergey, I think we should check your VALD linelist to make sure it was queried correctly; it looks like you may not have the ABO theory damping coefficient. For the 8662 line, I see your VDW values are -7.675ish, while the ABO value should be 291.275 (Adam has correctly implemented parsing this as far as I can tell; details here https://www.astro.uu.se/~barklem/howto.html). I don't know how big of an effect this could be or whether it is sufficient to explain the difference, but at least we should fix that.

**Comment by ajwheeler** [comment]
Here's a zoomed-in version of the plot above showing that the atmospheric structure makes a huge difference, but doesn't fix the discrepancy--it makes it just as large in the opposite direction.  The Ca II line in the Korg + PHOENIX spectrum is wider than the PHOENIX spectrum instead of narrower.  I agree that the broadening parameters are likely to be important, which is why I'm very curious about the potential "special treatment" in PHOENIX.

![image](https://user-images.githubusercontent.com/711963/202347415-943b756d-2469-4e03-85ea-074ed07bc9d7.png)

> I took a quick look at the parser, it should be getting the VDW coefficient from the line list so not using the default Unsold approx.

This is correct.  The ABO calculation code is [here](https://github.com/ajwheeler/Korg.jl/blob/main/src/line_absorption.jl#L232) if you are curious.  I wouldn't bet my life on its correctness, but I think it's right. The linelist I've been using (including for the plot here) has the correct ABO parameter, so there is still unexplained disagreement.

**Comment by alexji** [comment]
Based on Peter's e-mail, can you maybe try running the 8662 (air) line, with damping values -7.760 instead of 291.275 (matching what VALD says is the Kurucz damping data instead of ABO)?

**Comment by ajwheeler** [comment]
I don't see anywhere the the -alpha becomes (1-alpha) in Turbospectrum, but I think it's correct.  (see https://www.astro.uu.se/~barklem/howto.html).  The fortran implementation on that page also uses (1-alpha):
```fortran
GV=(4./PI)**(XALPHA*0.5)*GAMMAF*1.E4*SIGMA
VBAR=SQRT(21173.*T*(1./1.008+1./(AWGT/UU)))
GV=GV*((VBAR/1.E4)**(1.-XALPHA))
```

ABO vs no ABO does not make a big difference.  Here's the above plot showing both Korg spectra computed with `-7.760` and `291.275` for the Ca II line.
![ABO vs no](https://user-images.githubusercontent.com/711963/202494333-e42e8c3b-b214-4367-8342-be26022668e1.png)

**Comment by andycasey** [comment]
Reviving this thread...

I think the discussion about Ca II special lines relates to [Allard et al. (2014)](https://ui.adsabs.harvard.edu/abs/2014AdSpR..54.1248A/abstract), which came out a little after the Husser et al. (2013) paper, so it would explain why they were pretty brief on it. But that Allard et al. (2014) paper discusses Ca II H & K lines, not Ca II triplet.

I made a comparison with Korg (1.0.1), MOOG, Turbospectrum, Synspec, and PHOENIX (existing spectra). I used the VALD line list and the same atmosphere for all syntheses. The vmic of 0.43 km/s is because that's what the PHOENIX spectra were computed with. I'm a little puzzled because this comparison shows that Korg's Ca II lines are broader than PHOENIX.

The PHOENIX spectra were computed with a different line list (which afaik we still cannot source). But everything else about the comparisons is as close as possible.

<img width="1883" height="1602" alt="Image" src="https://github.com/user-attachments/assets/5dd98293-c160-49e7-9da9-b7f40fa48970" />

**Comment by ajwheeler** [comment]
>  I'm a little puzzled because this comparison shows that Korg's Ca II lines are broader than PHOENIX.

I think that's consistent with the above thread?  If you use the PHOENIX atmosphere, Korg has broader lines. If you use the MARCS one with the same parameters, it has narrower lines.

**Comment by andycasey** [comment]
In some of these figures, yes, but not in Sergey’s original figure: https://github.com/ajwheeler/Korg.jl/issues/139#issue-1446617163

**Comment by alexji** [comment]
If I read/recall correctly, this is due to a lack of ABO damping for CaT in Sergey’s original figure. (Edit I take that back, I see Adam’s plot indicating it matters but is not that big of a difference. I think Adam is right that the results just indicate the model atmosphere, and it would imply your recent plot uses Phoenix atmospheres rather than MARCS )
